
/**
 * Represents the cardinal directions used for movement and door placement.
 */
export enum Direction {
  UP,
  DOWN,
  LEFT,
  RIGHT,
  NONE
}

/**
 * Represents a 2D vector with x and y coordinates.
 */
export interface Vector2 {
  /** The x-coordinate. */
  x: number;
  /** The y-coordinate. */
  y: number;
}

/**
 * Represents a base entity in the game world, including players, enemies, projectiles, and items.
 */
export interface Entity {
  /** Unique identifier for the entity. */
  id: string;
  /** Current position of the entity in the game world. */
  position: Vector2;
  /** Current velocity vector of the entity. */
  velocity: Vector2;
  /** Size of the entity (diameter or width/height depending on shape). */
  size: number;
  /** Color used for rendering the entity. */
  color: string;
  /** The type of the entity. */
  type: 'PLAYER' | 'ENEMY' | 'PROJECTILE' | 'ITEM' | 'BOSS';
  /** Specific variant for enemies (e.g., 'SHOOTER', 'TANK'). */
  variant?: 'BASIC' | 'SHOOTER' | 'DASHER' | 'TANK'; // Enemy types
  /** Time remaining until the entity can attack again (in milliseconds). */
  attackCooldown?: number; // Timer for shooting or dashing
  /** Current health points of the entity. */
  health: number;
  /** Maximum health points of the entity. */
  maxHealth: number;
  /** Damage dealt by the entity on contact or attack. */
  damage: number;
  /** Movement speed of the entity. */
  speed: number;
  /** Indicates if the entity is currently active in the game loop. */
  isActive: boolean;
  /** List of active modifiers affecting the entity (e.g., 'TRIPLE_SHOT'). */
  modifiers: string[]; // 'TRIPLE_SHOT', 'PIERCING', 'BIG_TEARS'
}

/**
 * Represents a projectile fired by a player or enemy.
 */
export interface Projectile extends Entity {
  /** The entity type that fired the projectile ('PLAYER' or 'ENEMY'). */
  owner: 'PLAYER' | 'ENEMY';
  /** Whether the projectile passes through enemies. */
  piercing: boolean;
  /** List of entity IDs that this projectile has already hit. */
  hitIds: string[]; // IDs of enemies already hit by this projectile
}

/**
 * Defines the possible types of collectible items in the game.
 */
export type ItemType = 'HEALTH' | 'DAMAGE' | 'SPEED' | 'TRIPLE_SHOT' | 'PIERCING' | 'BIG_TEARS';

/**
 * Represents a collectible item in the game world.
 */
export interface Item extends Entity {
  /** The specific type/effect of the item. */
  itemType: ItemType;
  /** The display name of the item. */
  name: string;
  /** A humorous, slang-filled description generated by AI. */
  description: string; // Generated by Gemini (Slang)
  /** A clear description of the item's statistical effect (e.g., "+1 Dmg"). */
  statDescription: string; // Hard stats (e.g. "+1 Dmg")
}

/**
 * Represents a single room in the dungeon grid.
 */
export interface Room {
  /** Unique identifier for the room. */
  id: string;
  /** The X coordinate of the room in the dungeon grid. */
  gridX: number;
  /** The Y coordinate of the room in the dungeon grid. */
  gridY: number;
  /** Whether the room has been cleared of enemies. */
  cleared: boolean;
  /** List of enemies currently in the room. */
  enemies: Entity[];
  /** List of items currently in the room. */
  items: Item[];
  /** Map of available doors in the room, keyed by direction. */
  doors: { [key in Direction]?: boolean };
  /** Indicates if this room contains the boss. */
  isBossRoom: boolean;
  /** Indicates if this room contains a free item. */
  isItemRoom: boolean;
}

/**
 * Represents the various states of the game lifecycle.
 */
export enum GameState {
  MENU,
  PLAYING,
  PAUSED,
  GAME_OVER,
  VICTORY,
  ITEM_PICKUP_ANIMATION
}

/**
 * Represents the statistical attributes of the player.
 */
export interface GameStats {
  /** The stat representing fire rate or attack speed. */
  tears: number; // Fire rate
  /** Damage dealt per projectile (Gen Alpha slang: Rizz). */
  rizz: number; // Damage
  /** Movement speed (Gen Alpha slang: Zoom). */
  speed: number; // Movement
  /** Attack range (not fully implemented in code but present in stats). */
  range: number;
  /** Speed of projectiles. */
  shotSpeed: number;
  /** Health taken or other penalty metric (Gen Alpha slang: Fanum Tax). */
  fanumTax: number; // Health taken
}
