
export enum Direction {
  UP,
  DOWN,
  LEFT,
  RIGHT,
  NONE
}

export interface Vector2 {
  x: number;
  y: number;
}

export interface Entity {
  id: string;
  position: Vector2;
  velocity: Vector2;
  size: number;
  color: string;
  type: 'PLAYER' | 'ENEMY' | 'PROJECTILE' | 'ITEM' | 'BOSS';
  variant?: 'BASIC' | 'SHOOTER' | 'DASHER' | 'TANK'; // Enemy types
  attackCooldown?: number; // Timer for shooting or dashing
  health: number;
  maxHealth: number;
  damage: number;
  speed: number;
  isActive: boolean;
  modifiers: string[]; // 'TRIPLE_SHOT', 'PIERCING', 'BIG_TEARS'
}

export interface Projectile extends Entity {
  owner: 'PLAYER' | 'ENEMY';
  piercing: boolean;
  hitIds: string[]; // IDs of enemies already hit by this projectile
}

export type ItemType = 'HEALTH' | 'DAMAGE' | 'SPEED' | 'TRIPLE_SHOT' | 'PIERCING' | 'BIG_TEARS';

export interface Item extends Entity {
  itemType: ItemType;
  name: string;
  description: string; // Generated by Gemini (Slang)
  statDescription: string; // Hard stats (e.g. "+1 Dmg")
}

export interface Room {
  id: string;
  gridX: number;
  gridY: number;
  cleared: boolean;
  enemies: Entity[];
  items: Item[];
  doors: { [key in Direction]?: boolean };
  isBossRoom: boolean;
  isItemRoom: boolean;
}

export enum GameState {
  MENU,
  PLAYING,
  PAUSED,
  GAME_OVER,
  VICTORY,
  ITEM_PICKUP_ANIMATION
}

export interface GameStats {
  tears: number; // Fire rate
  rizz: number; // Damage
  speed: number; // Movement
  range: number;
  shotSpeed: number;
  fanumTax: number; // Health taken
}
